# Generated by Django 3.2.16 on 2023-04-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_date', models.DateField()),
                ('description', models.CharField(max_length=250)),
                ('rating', models.CharField(max_length=25)),
                ('user_id', models.IntegerField()),
                ('vendor_id', models.IntegerField()),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
