# Generated by Django 3.2.16 on 2023-04-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('name', models.CharField(max_length=45)),
                ('phone_no', models.IntegerField()),
                ('email', models.CharField(max_length=45)),
                ('function_date', models.DateField()),
                ('details', models.CharField(db_column='Details', max_length=1000)),
                ('user_id', models.IntegerField()),
                ('vendor_id', models.IntegerField()),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
