# Generated by Django 3.2.16 on 2023-04-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_id', models.IntegerField()),
                ('about', models.CharField(max_length=4500)),
                ('services', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('package', models.CharField(max_length=150)),
                ('business_name', models.CharField(max_length=40)),
                ('any_link', models.CharField(max_length=500)),
                ('cost', models.IntegerField()),
            ],
            options={
                'db_table': 'service',
            },
        ),
    ]
