# Generated by Django 3.2.16 on 2023-04-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousWork',
            fields=[
                ('previous_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=45)),
                ('package_id', models.IntegerField()),
            ],
            options={
                'db_table': 'previous_work',
            },
        ),
    ]
